import json

nb_path = r'c:\tradeflow-ai\tools\kaggle\nb4_eval.ipynb'
with open(nb_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Find and replace the evaluate_all cell completely
eval_source = [
    "EVAL_FIELDS = {\n",
    "    'nomorBl':           3.0,\n",
    "    'tglBl':             2.0,\n",
    "    'pelabuhan_muat':    1.5,\n",
    "    'pelabuhan_bongkar': 1.5,\n",
    "    'container_no':      2.0,\n",
    "    'beratKotor':        2.5,\n",
    "    'hs_code':           3.0,\n",
    "    'namaKapal':         1.5,\n",
    "    'voyageNumber':      1.0,\n",
    "}\n",
    "\n",
    "def find_doc_image(doc_key, real_docs_dir, nb0_dir):\n",
    "    \"\"\"Find image for a doc_key.\n",
    "    Key insight: GT uses 'Hapag_Filled_1' but files are 'Hapag Filled 1.pdf' (spaces).\n",
    "    Try both underscore and space variants.\n",
    "    \"\"\"\n",
    "    doc_key_spaced = doc_key.replace('_', ' ')  # 'Hapag_Filled_1' -> 'Hapag Filled 1'\n",
    "    variants = [doc_key, doc_key_spaced, doc_key.lower(), doc_key_spaced.lower()]\n",
    "    exts = ['.pdf', '.png', '.jpg', '.jpeg', '.tiff', '.tif']\n",
    "\n",
    "    # Strategy 1: exact filename match with all variants\n",
    "    for name in variants:\n",
    "        for ext in exts:\n",
    "            candidate = real_docs_dir / f'{name}{ext}'\n",
    "            if candidate.exists():\n",
    "                return str(candidate)\n",
    "\n",
    "    # Strategy 2: scan all files, check if doc_key (normalized) is in filename\n",
    "    doc_key_norm = doc_key.lower().replace('_', ' ')\n",
    "    for f in real_docs_dir.iterdir():\n",
    "        if f.suffix.lower() in exts:\n",
    "            if doc_key_norm in f.stem.lower().replace('_', ' '):\n",
    "                return str(f)\n",
    "\n",
    "    # Strategy 3: nb0 augmented manifest\n",
    "    manifest_path = nb0_dir / 'dataset' / 'augmented_manifest.json'\n",
    "    if manifest_path.exists():\n",
    "        manifest = json.loads(manifest_path.read_text())\n",
    "        for item in manifest.get('train', []) + manifest.get('test', []):\n",
    "            if item.get('doc_id') == doc_key:\n",
    "                raw = str(item.get('path', ''))\n",
    "                if raw.startswith('./dataset'):\n",
    "                    p = raw.replace('./dataset', str(nb0_dir / 'dataset'), 1)\n",
    "                elif raw.startswith('/kaggle'):\n",
    "                    p = raw\n",
    "                else:\n",
    "                    p = str(nb0_dir / 'dataset' / raw.lstrip('/'))\n",
    "                if Path(p).exists():\n",
    "                    return p\n",
    "    return None\n",
    "\n",
    "def evaluate_all():\n",
    "    if not GT_PATH.exists():\n",
    "        print(f'File GT tidak ditemukan: {GT_PATH}')\n",
    "        return\n",
    "\n",
    "    gt_data = json.loads(GT_PATH.read_text())\n",
    "    field_scores   = {f: [] for f in EVAL_FIELDS}\n",
    "    insw_correct   = []\n",
    "\n",
    "    print('=== MEMULAI EVALUASI REAL INFERENCE ===\\n')\n",
    "\n",
    "    for doc_key, gt_doc in gt_data.items():\n",
    "        img_path = find_doc_image(doc_key, REAL_DOCS_DIR, NB0_INPUT)\n",
    "\n",
    "        if not img_path:\n",
    "            print(f'--- {doc_key} (SKIP: Image not found)')\n",
    "            continue\n",
    "\n",
    "        print(f'--- {doc_key} ({gt_doc.get(\"carrier\", \"?\")})')\n",
    "        print(f'    Image: {img_path}')\n",
    "\n",
    "        pred_json = predict_document(img_path)\n",
    "\n",
    "        ceisa = gt_doc.get('ceisa_fields', gt_doc)\n",
    "        insw_gt = gt_doc.get('insw_flag', False)\n",
    "        hs_pred = str(pred_json.get('hs_code', ''))\n",
    "        insw_pred = hs_pred.startswith('28')\n",
    "\n",
    "        for field, weight in EVAL_FIELDS.items():\n",
    "            gt_val   = ceisa.get('container_no_normalized') if field == 'container_no' and not ceisa.get(field) else ceisa.get(field)\n",
    "            pred_val = pred_json.get(field, '')\n",
    "            score    = calculate_anls(str(gt_val or ''), str(pred_val or ''))\n",
    "            field_scores[field].append(score)\n",
    "            icon = '\\u2705' if score >= 0.85 else '\\u274c'\n",
    "            print(f'  {icon} {field:20}: ANLS={score:.3f}  GT={gt_val!r}  Pred={pred_val!r}')\n",
    "\n",
    "        insw_match = (insw_pred == insw_gt)\n",
    "        insw_correct.append(insw_match)\n",
    "        insw_icon = '\\u2705' if insw_match else '\\u274c'\n",
    "        print(f'  {insw_icon} insw_flag          : GT={insw_gt} | Pred={insw_pred}')\n",
    "        print()\n",
    "\n",
    "    print('\\n' + '='*50)\n",
    "    print('=== HASIL AKHIR WEIGHTED ANLS SCORE ===')\n",
    "    print('='*50)\n",
    "\n",
    "    weighted_scores = []\n",
    "    for field, weight in EVAL_FIELDS.items():\n",
    "        scores = field_scores[field]\n",
    "        if not scores: continue\n",
    "        avg = np.mean(scores)\n",
    "        weighted_scores.extend([avg] * int(weight * 2))\n",
    "        status = '\\u2705 LULUS' if avg >= 0.85 else '\\u274c GAGAL'\n",
    "        print(f'{field:22} : {avg:.4f}  {status}')\n",
    "\n",
    "    if not weighted_scores:\n",
    "        print('\\u26a0\\ufe0f  Tidak ada dokumen yang berhasil dievaluasi!')\n",
    "        return\n",
    "\n",
    "    insw_accuracy = np.mean(insw_correct) if insw_correct else 0.0\n",
    "    insw_status   = '\\u2705 LULUS' if insw_accuracy >= 0.9 else '\\u274c GAGAL'\n",
    "    print(f'{\"INSW Flag Detection\":22} : {insw_accuracy:.4f}  {insw_status}')\n",
    "\n",
    "    final_anls = np.mean(weighted_scores)\n",
    "    print()\n",
    "    print(f'WEIGHTED ANLS RATA-RATA: {final_anls:.4f}')\n",
    "    print(f'INSW Detection Accuracy: {insw_accuracy:.4f}')\n",
    "    print()\n",
    "    if final_anls >= 0.85:\n",
    "        print('\\U0001f389 MODEL LULUS NFR-007 (Akurasi >= 85%)! Siap deployment.')\n",
    "    else:\n",
    "        print(f'\\u26a0\\ufe0f  Akurasi {final_anls:.1%} belum mencapai target 85%.')\n",
    "\n",
    "evaluate_all()\n"
]

for i, cell in enumerate(nb['cells']):
    if cell['cell_type'] == 'code' and 'EVAL_FIELDS' in ''.join(cell['source']):
        nb['cells'][i]['source'] = eval_source
        print(f"Replaced eval cell at index {i}")
        break

with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print("nb4 rewritten cleanly with underscore->space fix")
