"""
Script to regenerate all 6 fixed Kaggle notebooks.
Fixes: #1 MODEL_ID, #2 tglBl ISO8601, #3 Unsloth+rank32, #4 vessel+INSW eval, #5 Gemini embedding, #6 32 XGBoost features
"""
import json, os

# ─────────────────────────────────────────────────────────────────────────────
# NB1: Fix #2 — Normalize tglBl to ISO 8601 in synthetic GT
# ─────────────────────────────────────────────────────────────────────────────
nb1 = {
 "cells": [
  {"cell_type":"markdown","metadata":{},"source":["# TradeFlow AI — nb1_synthetic_generator (Pillar 1: Carrier-Faithful)\n","\n","**Tujuan**: Men-generate 1.500 dokumen CIPL sintetis yang *strukturnya* identik dengan 5 carrier utama.\n","**Fix #2**: `tglBl` di Ground Truth sekarang selalu dinormalisasi ke ISO 8601 (YYYY-MM-DD)."]},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":["!pip install -q faker reportlab pillow pdf2image"]},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":[
    "import os, json, random\n",
    "from datetime import datetime, timedelta\n",
    "from dateutil import parser as dateparser\n",
    "from faker import Faker\n",
    "from reportlab.pdfgen import canvas\n",
    "from reportlab.lib.pagesizes import A4\n",
    "from reportlab.lib.units import inch\n",
    "\n",
    "fake = Faker('id_ID')\n",
    "OUTPUT_DIR = './dataset/synthetic'\n",
    "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
    "\n",
    "CARRIERS = ['Hapag-Lloyd', 'MSC', 'Maersk', 'Evergreen', 'Cordelia']\n",
    "DATE_FORMATS = ['%d/%m/%Y', '%d-%b-%Y', '%B %d, %Y', '%Y-%m-%d', '%d.%m.%Y', '%d %B %Y', '%d-%m-%y']\n",
    "\n",
    "def parse_to_iso(date_str: str) -> str:\n",
    "    \"\"\"Parse any date string to ISO 8601 format YYYY-MM-DD. Fix #2.\"\"\"\n",
    "    try:\n",
    "        return dateparser.parse(date_str, dayfirst=True).strftime('%Y-%m-%d')\n",
    "    except Exception:\n",
    "        return '1970-01-01'\n"
  ]},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":[
    "def random_hs_code():\n",
    "    base = f\"{fake.random_int(10, 99)}{fake.random_int(10, 99)}\"\n",
    "    sub  = f\"{fake.random_int(10, 99)}\"\n",
    "    ext  = f\"{fake.random_int(10, 99)}\"\n",
    "    if random.random() > 0.5:\n",
    "        return f\"{base}.{sub}.{ext}\"\n",
    "    return f\"{base}{sub}{ext}\"\n",
    "\n",
    "def random_container():\n",
    "    prefix = random.choice(['HLXU','MEDU','MSCU','MRSU','EGHU','CRSU'])\n",
    "    nums   = f\"{fake.random_int(1000000, 9999999)}\"\n",
    "    if random.random() < 0.2:\n",
    "        return f\"{prefix} {nums}\"\n",
    "    return f\"{prefix}{nums}\"\n",
    "\n",
    "def random_date():\n",
    "    fmt = random.choice(DATE_FORMATS)\n",
    "    return fake.date_between(start_date='-5y', end_date='today').strftime(fmt)\n",
    "\n",
    "def random_weight():\n",
    "    val = random.uniform(1000.0, 25000.0)\n",
    "    r   = random.random()\n",
    "    if r < 0.6:   return f\"{val:.2f} KGS\", round(val, 2)\n",
    "    elif r < 0.9: return f\"{val:.2f} KGM\", round(val, 2)\n",
    "    else:         return f\"{val/1000:.3f} MTS\", round(val, 2)\n"
  ]},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":[
    "def draw_carrier_template(c, carrier, data):\n",
    "    if carrier == 'Hapag-Lloyd':\n",
    "        c.setFont('Times-Bold', 16)\n",
    "        c.drawString(0.5*inch, 11*inch, 'Hapag-Lloyd')\n",
    "        c.setFont('Times-Roman', 10)\n",
    "        c.drawString(5.5*inch, 11*inch, f\"B/L No: {data['nomorBl']}\")\n",
    "        c.drawString(0.5*inch, 9*inch, 'Port of Loading:')\n",
    "        c.drawString(0.5*inch, 8.8*inch, data['pelabuhan_muat'])\n",
    "        c.drawString(3.5*inch, 9*inch, 'Port of Discharge:')\n",
    "        c.drawString(3.5*inch, 8.8*inch, data['pelabuhan_bongkar'])\n",
    "        c.drawString(0.5*inch, 7*inch, 'Container No.')\n",
    "        c.drawString(0.5*inch, 6.8*inch, data['container_no'])\n",
    "        c.drawString(6*inch, 7*inch, 'Gross Weight')\n",
    "        c.drawString(6*inch, 6.8*inch, data['berat_raw'])\n",
    "    elif carrier == 'Evergreen':\n",
    "        c.setFont('Helvetica-Bold', 14)\n",
    "        c.drawString(3*inch, 11*inch, 'EVERGREEN LINE')\n",
    "        c.setFont('Helvetica', 8)\n",
    "        c.drawString(6*inch, 10.5*inch, f\"2. B/L No: {data['nomorBl']}\")\n",
    "        c.drawString(0.5*inch, 9*inch, '10. Port of Loading')\n",
    "        c.drawString(0.5*inch, 8.8*inch, data['pelabuhan_muat'])\n",
    "        c.drawString(0.5*inch, 8*inch, '11. Port of Discharge')\n",
    "        c.drawString(0.5*inch, 7.8*inch, data['pelabuhan_bongkar'])\n",
    "        c.drawString(0.5*inch, 6*inch, '15. Container No.')\n",
    "        c.drawString(0.5*inch, 5.8*inch, data['container_no'])\n",
    "        c.drawString(6.5*inch, 6*inch, '19. Gross Weight')\n",
    "        c.drawString(6.5*inch, 5.8*inch, data['berat_raw'])\n",
    "    else:\n",
    "        c.setFont('Helvetica-Bold', 20)\n",
    "        c.drawString(1*inch, 10.5*inch, f\"{carrier} BILL OF LADING\")\n",
    "        c.setFont('Helvetica', 10)\n",
    "        c.drawString(5.5*inch, 10.5*inch, f\"No: {data['nomorBl']}\")\n",
    "        c.drawString(1*inch, 9*inch, f\"POL: {data['pelabuhan_muat']}\")\n",
    "        c.drawString(4*inch, 9*inch, f\"POD: {data['pelabuhan_bongkar']}\")\n",
    "        c.drawString(1*inch, 7*inch, f\"CNTR: {data['container_no']}\")\n",
    "        c.drawString(4*inch, 7*inch, f\"WT: {data['berat_raw']}\")\n",
    "    c.setFont('Helvetica', 9)\n",
    "    c.drawString(0.5*inch, 5*inch, 'DESCRIPTION OF GOODS:')\n",
    "    c.drawString(0.5*inch, 4.8*inch, f\"{fake.sentence()} HS: {data['hs_code']}\")\n",
    "    c.drawString(5*inch, 2*inch, f\"Date: {data['tglBl_raw']}\")\n"
  ]},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":[
    "def generate_synthetic_doc(idx):\n",
    "    carrier    = random.choice(CARRIERS)\n",
    "    bl_number  = f\"{carrier[:3].upper()}{fake.random_int(1000000, 9999999)}\"\n",
    "    date_raw   = random_date()\n",
    "    date_iso   = parse_to_iso(date_raw)   # FIX #2: selalu simpan ISO 8601\n",
    "    weight_raw, weight_norm = random_weight()\n",
    "    cntr       = random_container()\n",
    "    hs         = random_hs_code()\n",
    "\n",
    "    data = {\n",
    "        'nomorBl':       bl_number,\n",
    "        'tglBl_raw':     date_raw,\n",
    "        'pelabuhan_muat': fake.city().upper() + ' PORT',\n",
    "        'pelabuhan_bongkar': fake.city().upper() + ' PORT',\n",
    "        'container_no':  cntr,\n",
    "        'berat_raw':     weight_raw,\n",
    "        'beratKotor':    weight_norm,\n",
    "        'hs_code':       hs\n",
    "    }\n",
    "\n",
    "    pdf_path = os.path.join(OUTPUT_DIR, f'synth_{idx:04d}.pdf')\n",
    "    c = canvas.Canvas(pdf_path, pagesize=A4)\n",
    "    draw_carrier_template(c, carrier, data)\n",
    "    c.save()\n",
    "\n",
    "    gt = {\n",
    "        'document_type': 'bill_of_lading',\n",
    "        'carrier':       carrier,\n",
    "        'nomorBl':       data['nomorBl'],\n",
    "        'tglBl':         date_iso,          # FIX #2: YYYY-MM-DD, bukan date_raw\n",
    "        'pelabuhan_muat': data['pelabuhan_muat'],\n",
    "        'pelabuhan_bongkar': data['pelabuhan_bongkar'],\n",
    "        'container_no':  data['container_no'].replace(' ', ''),\n",
    "        'beratKotor':    data['beratKotor'],\n",
    "        'hs_code':       data['hs_code'].replace('.', '')\n",
    "    }\n",
    "    with open(os.path.join(OUTPUT_DIR, f'synth_{idx:04d}.json'), 'w') as f:\n",
    "        json.dump(gt, f, indent=2)\n",
    "\n",
    "print('Generating 1,500 carrier-faithful synthetic documents...')\n",
    "for i in range(1500):\n",
    "    generate_synthetic_doc(i)\n",
    "print('Done! Output:', OUTPUT_DIR)\n"
  ]}
 ],
 "metadata": {
  "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open(r'c:\tradeflow-ai\tools\kaggle\nb1_synthetic_generator.ipynb', 'w') as f:
    json.dump(nb1, f, indent=1)
print("nb1 written")

# ─────────────────────────────────────────────────────────────────────────────
# NB3: Fix #1 (MODEL_ID), #3 (Unsloth + LoRA rank=32)
# ─────────────────────────────────────────────────────────────────────────────
nb3 = {
 "cells": [
  {"cell_type":"markdown","metadata":{},"source":[
    "# TradeFlow AI — nb3_olm_finetune (v4 — Unsloth + olmOCR-2-7B-1025)\n",
    "\n",
    "**Fix #1**: Model ID diubah ke `allenai/olmOCR-2-7B-1025` sesuai PRD §4 Decision 2.\n",
    "**Fix #3**: Menggunakan Unsloth (2× speed, 60% VRAM reduction) + LoRA rank=32 sesuai PRD §10.4.\n",
    "\n",
    "| Phase | Data | LoRA |\n",
    "|---|---|---|\n",
    "| 1: Synthetic SFT | 1.500 CIPL sintetis | r=32 |\n",
    "| 2: Mixed | 80% sintetis + 20% real aug | r=32 |\n"
  ]},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":[
    "# Unsloth dulu, baru yang lain (urutan wajib)\n",
    "!pip install -q unsloth[colab-new]\n",
    "!pip install -q peft datasets accelerate bitsandbytes trl qwen-vl-utils\n",
    "!pip install -q pdf2image pillow python-dateutil\n",
    "!apt-get update -qq && apt-get install -qq poppler-utils\n"
  ]},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":[
    "import json, os, gc\n",
    "import torch\n",
    "import numpy as np\n",
    "from pathlib import Path\n",
    "from PIL import Image\n",
    "from pdf2image import convert_from_path\n",
    "from datasets import Dataset\n",
    "from kaggle_secrets import UserSecretsClient\n",
    "\n",
    "# FIX #1: Model ID yang benar sesuai PRD\n",
    "MODEL_ID = 'allenai/olmOCR-2-7B-1025'\n",
    "OUT_DIR  = Path('./olmocr-tradeflow-lora')\n",
    "OUT_DIR.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "NB0_INPUT     = Path('/kaggle/input/nb0-real-doc-augmentation')\n",
    "NB1_INPUT     = Path('/kaggle/input/nb1-synthetic-generator')\n",
    "MANIFEST_PATH = NB0_INPUT / 'dataset' / 'augmented_manifest.json'\n",
    "SYNTHETIC_DIR = NB1_INPUT / 'dataset' / 'synthetic'\n",
    "GT_PATH       = Path('/kaggle/input/tradeflow-real-docs/TradeFlow_GroundTruth_v5.2.json')\n",
    "\n",
    "try:\n",
    "    user_secrets = UserSecretsClient()\n",
    "    hf_token = user_secrets.get_secret('HF_TOKEN')\n",
    "except:\n",
    "    hf_token = None\n",
    "    print('Warning: HF_TOKEN not found.')\n",
    "\n",
    "DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'\n",
    "print(f'Device : {DEVICE}')\n",
    "if DEVICE == 'cuda':\n",
    "    print(f'GPU    : {torch.cuda.get_device_name(0)}')\n",
    "    print(f'VRAM   : {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')\n"
  ]},
  {"cell_type":"markdown","metadata":{},"source":["## 1. Load Model dengan Unsloth (FIX #3)"]},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":[
    "from unsloth import FastVisionModel\n",
    "\n",
    "print(f'Loading {MODEL_ID} via Unsloth (2x speed, 60% VRAM reduction)...')\n",
    "model, processor = FastVisionModel.from_pretrained(\n",
    "    model_name=MODEL_ID,\n",
    "    load_in_4bit=True,\n",
    "    use_gradient_checkpointing='unsloth',  # Kaggle-optimised checkpointing\n",
    "    token=hf_token,\n",
    ")\n",
    "\n",
    "# FIX #3: LoRA rank=32 sesuai PRD §10.4\n",
    "model = FastVisionModel.get_peft_model(\n",
    "    model,\n",
    "    r=32,\n",
    "    lora_alpha=64,\n",
    "    target_modules=['q_proj','v_proj','k_proj','o_proj'],\n",
    "    lora_dropout=0.05,\n",
    "    bias='none',\n",
    "    use_gradient_checkpointing='unsloth',\n",
    ")\n",
    "model.print_trainable_parameters()\n"
  ]},
  {"cell_type":"markdown","metadata":{},"source":["## 2. Dataset Preparation (Multimodal)"]},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":[
    "def load_image(path_str):\n",
    "    if str(path_str).endswith('.pdf'):\n",
    "        pages = convert_from_path(path_str, dpi=150, first_page=1, last_page=1)\n",
    "        return pages[0].convert('RGB')\n",
    "    return Image.open(path_str).convert('RGB')\n",
    "\n",
    "def create_qwen_message(img_path, json_str):\n",
    "    return {\n",
    "        'messages': [\n",
    "            {'role':'user','content':[\n",
    "                {'type':'image'},\n",
    "                {'type':'text','text':'Extract CEISA fields from this shipping document. Return JSON with: nomorBl, tglBl, pelabuhan_muat, pelabuhan_bongkar, container_no, beratKotor, hs_code, namaKapal, voyageNumber.'}\n",
    "            ]},\n",
    "            {'role':'assistant','content':[{'type':'text','text':json_str}]}\n",
    "        ],\n",
    "        'image_path': img_path\n",
    "    }\n",
    "\n",
    "gt_data = json.loads(GT_PATH.read_text()) if GT_PATH.exists() else {}\n",
    "dataset_examples = []\n",
    "\n",
    "# A. Real augmented docs (TRAIN split only)\n",
    "if MANIFEST_PATH.exists():\n",
    "    manifest = json.loads(MANIFEST_PATH.read_text())\n",
    "    for item in manifest.get('train', []):\n",
    "        doc_id = item['doc_id']\n",
    "        if doc_id in gt_data:\n",
    "            img_path = str(item['path']).replace('./dataset', str(NB0_INPUT/'dataset'))\n",
    "            fields = gt_data[doc_id].get('ceisa_fields', gt_data[doc_id])\n",
    "            dataset_examples.append(create_qwen_message(img_path, json.dumps(fields)))\n",
    "    print(f'Loaded {len(dataset_examples)} real augmented images.')\n",
    "\n",
    "# B. Synthetic docs (300 samples for first run)\n",
    "synth_count = 0\n",
    "if SYNTHETIC_DIR.exists():\n",
    "    for json_file in list(SYNTHETIC_DIR.glob('*.json'))[:300]:\n",
    "        pdf_file = json_file.with_suffix('.pdf')\n",
    "        if pdf_file.exists():\n",
    "            gt_json = json.loads(json_file.read_text())\n",
    "            dataset_examples.append(create_qwen_message(str(pdf_file), json.dumps(gt_json)))\n",
    "            synth_count += 1\n",
    "    print(f'Loaded {synth_count} synthetic documents.')\n",
    "\n",
    "train_dataset = Dataset.from_list(dataset_examples)\n",
    "print(f'Total training examples: {len(train_dataset)}')\n"
  ]},
  {"cell_type":"markdown","metadata":{},"source":["## 3. Custom Data Collator (Qwen2-VL)"]},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":[
    "class Qwen2VLDataCollator:\n",
    "    def __init__(self, processor):\n",
    "        self.processor = processor\n",
    "\n",
    "    def __call__(self, examples):\n",
    "        texts, images = [], []\n",
    "        for ex in examples:\n",
    "            texts.append(self.processor.apply_chat_template(ex['messages'], tokenize=False, add_generation_prompt=False))\n",
    "            images.append(load_image(ex['image_path']))\n",
    "        batch = self.processor(text=texts, images=images, return_tensors='pt', padding=True)\n",
    "        labels = batch['input_ids'].clone()\n",
    "        labels[labels == self.processor.tokenizer.pad_token_id] = -100\n",
    "        batch['labels'] = labels\n",
    "        return batch\n",
    "\n",
    "data_collator = Qwen2VLDataCollator(processor)\n"
  ]},
  {"cell_type":"markdown","metadata":{},"source":["## 4. Training (Unsloth SFTTrainer)"]},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":[
    "from transformers import TrainingArguments, Trainer\n",
    "\n",
    "FastVisionModel.for_training(model)  # Aktifkan Unsloth training mode\n",
    "\n",
    "training_args = TrainingArguments(\n",
    "    output_dir='./olmocr-tradeflow-lora/final',\n",
    "    learning_rate=1e-4,\n",
    "    num_train_epochs=1,             # Naikkan ke 3 untuk full training\n",
    "    per_device_train_batch_size=1,  # T4 VRAM safety\n",
    "    gradient_accumulation_steps=8,  # Effective batch = 8\n",
    "    warmup_ratio=0.05,\n",
    "    weight_decay=0.01,\n",
    "    logging_steps=10,\n",
    "    save_strategy='no',\n",
    "    remove_unused_columns=False,    # CRITICAL for custom collator\n",
    "    fp16=True,\n",
    "    optim='adamw_8bit',             # Unsloth 8-bit optimizer\n",
    ")\n",
    "\n",
    "trainer = Trainer(\n",
    "    model=model,\n",
    "    args=training_args,\n",
    "    train_dataset=train_dataset,\n",
    "    data_collator=data_collator,\n",
    ")\n",
    "\n",
    "print('=== Mulai Training Qwen2-VL via Unsloth ===')\n",
    "trainer.train()\n",
    "print('Training selesai. Menyimpan model...')\n",
    "trainer.model.save_pretrained(OUT_DIR / 'best')\n"
  ]},
  {"cell_type":"markdown","metadata":{},"source":["## 5. Upload ke HuggingFace Hub"]},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":[
    "HF_REPO_NAME = 'muhammadghiffari/olm-ocr-cipl-v1'\n",
    "\n",
    "if hf_token:\n",
    "    from huggingface_hub import HfApi\n",
    "    api = HfApi(token=hf_token)\n",
    "    api.create_repo(repo_id=HF_REPO_NAME, exist_ok=True)\n",
    "    trainer.model.push_to_hub(HF_REPO_NAME, token=hf_token)\n",
    "    processor.push_to_hub(HF_REPO_NAME, token=hf_token)\n",
    "    print(f'Model berhasil diupload ke: https://huggingface.co/{HF_REPO_NAME}')\n",
    "else:\n",
    "    print('HF_TOKEN tidak ditemukan. Simpan manual dari OUT_DIR.')\n"
  ]}
 ],
 "metadata": {
  "accelerator": "GPU",
  "colab": {"gpuType": "T4"},
  "kernelspec": {"display_name": "Python 3 (ipykernel)", "language": "python", "name": "python3"},
  "language_info": {"name": "python", "version": "3.10.12"}
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

with open(r'c:\tradeflow-ai\tools\kaggle\nb3_olm_finetune.ipynb', 'w') as f:
    json.dump(nb3, f, indent=1)
print("nb3 written")

# ─────────────────────────────────────────────────────────────────────────────
# NB4: Fix #4 — Add namaKapal, voyageNumber, INSW flag evaluation
# ─────────────────────────────────────────────────────────────────────────────
nb4 = {
 "cells": [
  {"cell_type":"markdown","metadata":{},"source":[
    "# TradeFlow AI — nb4_eval (Final Evaluation)\n",
    "\n",
    "**Fix #4**: Menambah evaluasi field `namaKapal`, `voyageNumber`, dan `insw_flag` sesuai Ground Truth v5.2.\n",
    "Menghitung skor ANLS per field untuk memastikan NFR-007 (Akurasi >= 85%) tercapai.\n"
  ]},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":[
    "!pip install -q rapidfuzz transformers peft accelerate pillow bitsandbytes\n"
  ]},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":[
    "import os, json\n",
    "from pathlib import Path\n",
    "import torch\n",
    "from rapidfuzz import fuzz\n",
    "import numpy as np\n",
    "from PIL import Image\n",
    "from transformers import Qwen2VLForConditionalGeneration, AutoProcessor, BitsAndBytesConfig\n",
    "from peft import PeftModel\n",
    "\n",
    "def calculate_anls(gt_val, pred_val, threshold=0.5):\n",
    "    if not gt_val and not pred_val: return 1.0\n",
    "    if not gt_val or not pred_val: return 0.0\n",
    "    gt_str, pred_str = str(gt_val).lower().strip(), str(pred_val).lower().strip()\n",
    "    ed    = 1.0 - (fuzz.ratio(gt_str, pred_str) / 100.0)\n",
    "    score = 1.0 - ed\n",
    "    return score if score >= threshold else 0.0\n",
    "\n",
    "REAL_DOCS_DIR = Path('/kaggle/input/tradeflow-real-docs')\n",
    "GT_PATH       = REAL_DOCS_DIR / 'TradeFlow_GroundTruth_v5.2.json'\n",
    "\n",
    "# FIX #1 applied here too: model ID corrected\n",
    "BASE_MODEL_ID  = 'allenai/olmOCR-2-7B-1025'\n",
    "LORA_ADAPTER_ID = 'muhammadghiffari/olm-ocr-cipl-v1'\n",
    "\n",
    "IS_SIMULATION = True  # Ubah ke False untuk run inferensi nyata\n"
  ]},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":[
    "print('Memuat Base Model & LoRA Adapter...')\n",
    "\n",
    "if not IS_SIMULATION:\n",
    "    processor = AutoProcessor.from_pretrained(BASE_MODEL_ID)\n",
    "    qconfig   = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_compute_dtype=torch.float16)\n",
    "    base_model = Qwen2VLForConditionalGeneration.from_pretrained(\n",
    "        BASE_MODEL_ID, quantization_config=qconfig, device_map='auto'\n",
    "    )\n",
    "    model = PeftModel.from_pretrained(base_model, LORA_ADAPTER_ID)\n",
    "    model.eval()\n",
    "    print('Model siap!')\n",
    "else:\n",
    "    print('[MODE SIMULASI] Model tidak dimuat — menampilkan evaluasi struktur GT.')\n"
  ]},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":[
    "# FIX #4: Extended field list sesuai Ground Truth v5.2\n",
    "# Setiap field memiliki bobot (weight) untuk weighted ANLS score\n",
    "EVAL_FIELDS = {\n",
    "    'nomorBl':           3.0,  # Kunci primer CEISA\n",
    "    'tglBl':             2.0,  # Format tanggal sering error\n",
    "    'pelabuhan_muat':    1.5,\n",
    "    'pelabuhan_bongkar': 1.5,\n",
    "    'container_no':      2.0,  # ISO 6346 normalization\n",
    "    'beratKotor':        2.5,  # Unit conversion MTS/KGS\n",
    "    'hs_code':           3.0,  # Penyebab penolakan #1\n",
    "    # FIX #4: Field baru\n",
    "    'namaKapal':         1.5,  # Vessel validation (PRD §5: VesselValidationAgent)\n",
    "    'voyageNumber':      1.0,  # Cross-check AIS\n",
    "}\n",
    "\n",
    "def evaluate_all():\n",
    "    if not GT_PATH.exists():\n",
    "        print(f'File GT tidak ditemukan: {GT_PATH}')\n",
    "        return\n",
    "\n",
    "    gt_data = json.loads(GT_PATH.read_text())\n",
    "    field_scores   = {f: [] for f in EVAL_FIELDS}\n",
    "    insw_correct   = []   # FIX #4: Track INSW flag detection\n",
    "\n",
    "    print('\\n=== MEMULAI EVALUASI (9 Fields + INSW Flag) ===\\n')\n",
    "\n",
    "    for doc_key, gt_doc in gt_data.items():\n",
    "        print(f'--- {doc_key} ({gt_doc.get(\"carrier\", \"?\")})')\n",
    "\n",
    "        ceisa = gt_doc.get('ceisa_fields', gt_doc)\n",
    "        insw_gt = gt_doc.get('insw_flag', False)\n",
    "\n",
    "        if IS_SIMULATION:\n",
    "            # Mock dengan sedikit noise (20% chance error per field)\n",
    "            pred_json = dict(ceisa)\n",
    "            if np.random.random() < 0.2:\n",
    "                pred_json['container_no'] = str(pred_json.get('container_no', '')) + 'X'\n",
    "            # Mock INSW detection: model assume no INSW unless HS code starts with '28'\n",
    "            hs_pred = str(pred_json.get('hs_code', ''))\n",
    "            insw_pred = hs_pred.startswith('28')  # Simple heuristic for simulation\n",
    "        else:\n",
    "            # REAL INFERENCE (implementasi nyata di sini)\n",
    "            pred_json = {}  # Ganti dengan kode inferensi asli\n",
    "            insw_pred = False\n",
    "\n",
    "        # Evaluasi per field\n",
    "        for field, weight in EVAL_FIELDS.items():\n",
    "            gt_val   = ceisa.get(field) or ceisa.get('container_no_normalized') if field == 'container_no' else ceisa.get(field)\n",
    "            pred_val = pred_json.get(field, '')\n",
    "            score    = calculate_anls(str(gt_val or ''), str(pred_val or ''))\n",
    "            field_scores[field].append(score)\n",
    "            icon = '✅' if score >= 0.85 else '❌'\n",
    "            print(f'  {icon} {field:20}: ANLS {score:.3f} (weight={weight:.1f})')\n",
    "\n",
    "        # FIX #4: INSW flag evaluation\n",
    "        insw_match = (insw_pred == insw_gt)\n",
    "        insw_correct.append(insw_match)\n",
    "        insw_icon = '✅' if insw_match else '❌'\n",
    "        print(f'  {insw_icon} insw_flag          : GT={insw_gt} | Pred={insw_pred}')\n",
    "        print()\n",
    "\n",
    "    # Final report\n",
    "    print('\\n' + '='*50)\n",
    "    print('=== HASIL AKHIR WEIGHTED ANLS SCORE ===')\n",
    "    print('='*50)\n",
    "\n",
    "    weighted_scores = []\n",
    "    for field, weight in EVAL_FIELDS.items():\n",
    "        scores = field_scores[field]\n",
    "        if not scores: continue\n",
    "        avg = np.mean(scores)\n",
    "        weighted_scores.extend([avg] * int(weight * 2))\n",
    "        status = '✅ LULUS' if avg >= 0.85 else '❌ GAGAL'\n",
    "        print(f'{field:22} : {avg:.4f}  {status}')\n",
    "\n",
    "    insw_accuracy = np.mean(insw_correct) if insw_correct else 0.0\n",
    "    insw_status   = '✅ LULUS' if insw_accuracy >= 0.9 else '❌ GAGAL'\n",
    "    print(f'{\"INSW Flag Detection\":22} : {insw_accuracy:.4f}  {insw_status}')\n",
    "\n",
    "    final_anls = np.mean(weighted_scores) if weighted_scores else 0.0\n",
    "    print()\n",
    "    print(f'WEIGHTED ANLS RATA-RATA: {final_anls:.4f}')\n",
    "    print(f'INSW Detection Accuracy: {insw_accuracy:.4f}')\n",
    "\n",
    "    print()\n",
    "    if final_anls >= 0.85:\n",
    "        print('🎉 MODEL LULUS NFR-007 (Akurasi >= 85%)! Siap untuk deployment.')\n",
    "    else:\n",
    "        print(f'⚠️  Akurasi {final_anls:.1%} belum mencapai target 85%. Perlu training lebih lanjut.')\n",
    "\n",
    "evaluate_all()\n"
  ]}
 ],
 "metadata": {
  "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open(r'c:\tradeflow-ai\tools\kaggle\nb4_eval.ipynb', 'w') as f:
    json.dump(nb4, f, indent=1)
print("nb4 written")

# ─────────────────────────────────────────────────────────────────────────────
# NB2: Fix #5 — Add Gemini embedding function note + richer BTKI data
# ─────────────────────────────────────────────────────────────────────────────
nb2 = {
 "cells": [
  {"cell_type":"markdown","metadata":{},"source":[
    "# TradeFlow AI — nb2_chromadb_index\n",
    "\n",
    "Generates the HS code ChromaDB vector index.\n",
    "**Fix #5 (Production note)**: Untuk produksi nyata, ganti `embedding_function` default dengan Gemini Text Embedding (sesuai PRD §3: 'ChromaDB + Gemini reranker').\n"
  ]},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":[
    "!pip install -q chromadb sentence-transformers pandas\n"
  ]},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":[
    "import chromadb\n",
    "import pandas as pd\n",
    "\n",
    "client     = chromadb.PersistentClient(path='./chroma_db')\n",
    "collection = client.get_or_create_collection(name='hs_codes')\n",
    "\n",
    "# NOTE untuk produksi: ganti embedding_function di atas dengan:\n",
    "# from chromadb.utils.embedding_functions import GoogleGenerativeAiEmbeddingFunction\n",
    "# ef = GoogleGenerativeAiEmbeddingFunction(api_key=GEMINI_API_KEY, model_name='models/text-embedding-004')\n",
    "# collection = client.get_or_create_collection(name='hs_codes', embedding_function=ef)\n",
    "\n",
    "data = [\n",
    "    # --- KUNCI JAWABAN dari Ground Truth v5.2 ---\n",
    "    {'hs':'84821000','desc':'Bantalan peluru. Ball bearings. Bearings & bearing units.'},\n",
    "    {'hs':'84822000','desc':'Bantalan rol tirus, termasuk rakitan kerucut dan rol tirus. Tapered roller bearings.'},\n",
    "    {'hs':'84825000','desc':'Bantalan rol silinder lainnya. Other cylindrical roller bearings.'},\n",
    "    {'hs':'84828000','desc':'Lain-lain, termasuk bantalan kombinasi peluru atau rol. Other combined bearings.'},\n",
    "    {'hs':'28151110','desc':'Natrium hidroksida (soda kaustik) dalam bentuk padat. Caustic Soda Flakes. UN1813 Class 8 Dangerous Goods.'},\n",
    "    {'hs':'72193590','desc':'Produk canai lincin dari baja tahan karat. Cold Rolled Stainless Steel Coil. Grade J3.'},\n",
    "    # --- Data Pengecoh (Automotive) ---\n",
    "    {'hs':'87070000','desc':'Bodi untuk kendaraan bermotor. Bodies for motor vehicles.'},\n",
    "    {'hs':'87071010','desc':'Bodi Untuk gokart dan mobil golf. For go-karts and golf cars.'},\n",
    "    {'hs':'87079021','desc':'Bodi Untuk mobil termasuk limousin. For motor cars including stretch limousines.'},\n",
    "    {'hs':'87080000','desc':'Bagian dan aksesori kendaraan bermotor. Parts and accessories of motor vehicles.'},\n",
    "    {'hs':'87082100','desc':'Sabuk pengaman. Safety seat belts.'},\n",
    "    {'hs':'87082200','desc':'Kaca depan windshield, jendela belakang. Front windscreens windshields rear windows.'},\n",
    "    # --- Data Tambahan (Chemical / Fertilizer) ---\n",
    "    {'hs':'31021000','desc':'Urea mengandung lebih dari 45% nitrogen. Urea PRILLED UREA nitrogen fertilizer.'},\n",
    "    {'hs':'39269099','desc':'Artikel lain dari plastik. Other articles of plastics.'},\n",
    "    {'hs':'84713020','desc':'Mesin pengolah data otomatis portabel laptop. Portable automatic data processing machines laptops.'},\n",
    "]\n",
    "\n",
    "df = pd.DataFrame(data)\n",
    "print(f'Indexing {len(df)} HS codes into ChromaDB...')\n",
    "collection.add(\n",
    "    documents=df['desc'].tolist(),\n",
    "    metadatas=[{'hs_code': hs} for hs in df['hs']],\n",
    "    ids=df['hs'].tolist()\n",
    ")\n",
    "print('Indexing complete. Database saved to ./chroma_db')\n"
  ]}
 ],
 "metadata": {
  "kernelspec": {"display_name": ".venv", "language": "python", "name": "python3"},
  "language_info": {"name": "python", "version": "3.13.0"}
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open(r'c:\tradeflow-ai\tools\kaggle\nb2_chromadb_index.ipynb', 'w') as f:
    json.dump(nb2, f, indent=1)
print("nb2 written")

# ─────────────────────────────────────────────────────────────────────────────
# NB5: Fix #6 — 32 features matching PRD (with maritime signal stubs)
# ─────────────────────────────────────────────────────────────────────────────
nb5 = {
 "cells": [
  {"cell_type":"markdown","metadata":{},"source":[
    "# TradeFlow AI — nb5_xgboost\n",
    "\n",
    "**Fix #6**: Ditingkatkan dari 3 fitur menjadi 32 fitur sesuai PRD §11.\n",
    "Maritime signals (vessel_voyage_match, port_congestion_index) disertakan sebagai stub — akan diisi dengan data nyata saat sistem produksi berjalan.\n"
  ]},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":[
    "!pip install -q xgboost pandas numpy scikit-learn\n"
  ]},
  {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":[
    "import xgboost as xgb\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import roc_auc_score, accuracy_score, classification_report\n",
    "\n",
    "print('Generating mock dataset: 5,000 historical declarations with 32 features...')\n",
    "np.random.seed(42)\n",
    "n = 5000\n",
    "\n",
    "# === CORE DOCUMENT FEATURES (12) ===\n",
    "crs_score        = np.clip(np.random.normal(70, 15, n), 0, 100)\n",
    "correction_count = np.random.poisson(1.2, n)\n",
    "agent_agreement  = np.random.uniform(0.55, 1.0, n)\n",
    "hs_confidence    = np.random.uniform(0.4, 1.0, n)   # ChromaDB RAG top-1 score\n",
    "field_low_count  = np.random.poisson(0.8, n)         # Fields flagged LOW confidence\n",
    "field_missing_count = np.random.poisson(0.3, n)\n",
    "has_hs_code      = np.random.binomial(1, 0.85, n)    # 15% docs lack HS code\n",
    "doc_page_count   = np.random.choice([1, 2, 3], n, p=[0.5, 0.35, 0.15])\n",
    "has_watermark    = np.random.binomial(1, 0.7, n)\n",
    "is_scanned       = np.random.binomial(1, 0.4, n)\n",
    "carrier_code     = np.random.choice([0,1,2,3,4], n)  # HLCU=0, MSCU=1, MAEU=2, EGLV=3, CSLU=4\n",
    "incoterm_code    = np.random.choice([0,1,2], n)       # CFR=0, FOB=1, CIF=2\n",
    "\n",
    "# === CEISA VALIDATION FEATURES (8) ===\n",
    "nib_valid        = np.random.binomial(1, 0.9, n)\n",
    "npwp_valid       = np.random.binomial(1, 0.88, n)\n",
    "hs_format_valid  = np.random.binomial(1, 0.92, n)    # 8-digit format\n",
    "date_parseable   = np.random.binomial(1, 0.95, n)\n",
    "weight_converted = np.random.binomial(1, 0.93, n)    # MTS/KGS/KGM resolved\n",
    "container_iso    = np.random.binomial(1, 0.91, n)    # ISO 6346 compliant\n",
    "cross_doc_rules_pass = np.clip(np.random.normal(8, 1.5, n), 0, 11).astype(int)\n",
    "insw_flag        = np.random.binomial(1, 0.05, n)    # 5% declarations trigger INSW\n",
    "\n",
    "# === MARITIME SIGNALS (7) — Stub: populated from AIS/Vessel data in production ===\n",
    "vessel_voyage_match    = np.random.binomial(1, 0.88, n)  # AIS cross-check result\n",
    "port_congestion_index  = np.random.uniform(0, 1, n)      # From port lineup data\n",
    "carrier_rejection_30d  = np.random.uniform(0.05, 0.35, n) # Historical carrier rejection rate\n",
    "route_risk_score       = np.random.uniform(0, 1, n)      # Origin-destination risk\n",
    "vessel_flag_risk       = np.random.binomial(1, 0.03, n)  # High-risk flag state\n",
    "avg_transit_days       = np.random.normal(21, 7, n)\n",
    "cargo_category_risk    = np.random.choice([0,1,2], n, p=[0.7, 0.25, 0.05])  # 0=normal,1=restricted,2=DG\n",
    "\n",
    "# === HISTORICAL FEATURES (5) ===\n",
    "importer_rejection_rate   = np.random.uniform(0, 0.5, n)\n",
    "importer_declaration_count = np.random.poisson(50, n)\n",
    "hs_code_rejection_rate    = np.random.uniform(0, 0.4, n)\n",
    "avg_operator_correction   = np.random.uniform(0.5, 3, n)\n",
    "days_since_last_rejection = np.clip(np.random.exponential(30, n), 1, 365)\n",
    "\n",
    "df = pd.DataFrame({\n",
    "    # Core\n",
    "    'crs_score':crs_score, 'correction_count':correction_count, 'agent_agreement':agent_agreement,\n",
    "    'hs_confidence':hs_confidence, 'field_low_count':field_low_count, 'field_missing_count':field_missing_count,\n",
    "    'has_hs_code':has_hs_code, 'doc_page_count':doc_page_count, 'has_watermark':has_watermark,\n",
    "    'is_scanned':is_scanned, 'carrier_code':carrier_code, 'incoterm_code':incoterm_code,\n",
    "    # CEISA\n",
    "    'nib_valid':nib_valid, 'npwp_valid':npwp_valid, 'hs_format_valid':hs_format_valid,\n",
    "    'date_parseable':date_parseable, 'weight_converted':weight_converted, 'container_iso':container_iso,\n",
    "    'cross_doc_rules_pass':cross_doc_rules_pass, 'insw_flag':insw_flag,\n",
    "    # Maritime\n",
    "    'vessel_voyage_match':vessel_voyage_match, 'port_congestion_index':port_congestion_index,\n",
    "    'carrier_rejection_30d':carrier_rejection_30d, 'route_risk_score':route_risk_score,\n",
    "    'vessel_flag_risk':vessel_flag_risk, 'avg_transit_days':avg_transit_days,\n",
    "    'cargo_category_risk':cargo_category_risk,\n",
    "    # Historical\n",
    "    'importer_rejection_rate':importer_rejection_rate, 'importer_declaration_count':importer_declaration_count,\n",
    "    'hs_code_rejection_rate':hs_code_rejection_rate, 'avg_operator_correction':avg_operator_correction,\n",
    "    'days_since_last_rejection':days_since_last_rejection,\n",
    "})\n",
    "\n",
    "# Label generation (correlated with risk signals)\n",
    "risk = (\n",
    "    (100 - crs_score) * 0.02 +\n",
    "    correction_count * 0.3 +\n",
    "    (1 - agent_agreement) * 2 +\n",
    "    (1 - hs_confidence) * 1.5 +\n",
    "    insw_flag * 2 +\n",
    "    (1 - vessel_voyage_match) * 1.2 +\n",
    "    carrier_rejection_30d * 2\n",
    ")\n",
    "prob_reject = 1 / (1 + np.exp(-risk + 4))\n",
    "labels      = np.random.binomial(1, prob_reject)\n",
    "df['rejected'] = labels\n",
    "\n",
    "print(f'Dataset: {len(df)} samples, {df.columns.tolist().count(\".\") + len(df.columns)} features')\n",
    "print(f'Rejection rate: {labels.mean():.1%}')\n",
    "\n",
    "X = df.drop('rejected', axis=1)\n",
    "y = df['rejected']\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n",
    "\n",
    "dtrain = xgb.DMatrix(X_train, label=y_train, feature_names=X.columns.tolist())\n",
    "dtest  = xgb.DMatrix(X_test, label=y_test, feature_names=X.columns.tolist())\n",
    "\n",
    "params = {\n",
    "    'objective': 'binary:logistic',\n",
    "    'eval_metric': ['auc', 'logloss'],\n",
    "    'max_depth': 6,\n",
    "    'eta': 0.05,\n",
    "    'subsample': 0.8,\n",
    "    'colsample_bytree': 0.8,\n",
    "    'min_child_weight': 5,\n",
    "    'scale_pos_weight': (y==0).sum() / (y==1).sum(),  # Class imbalance correction\n",
    "}\n",
    "\n",
    "print('Training XGBoost (32 features)...')\n",
    "evals = [(dtrain, 'train'), (dtest, 'eval')]\n",
    "bst   = xgb.train(params, dtrain, num_boost_round=200, evals=evals, early_stopping_rounds=20, verbose_eval=50)\n",
    "\n",
    "preds     = bst.predict(dtest)\n",
    "auc       = roc_auc_score(y_test, preds)\n",
    "acc       = accuracy_score(y_test, (preds > 0.5).astype(int))\n",
    "print(f'\\nTest AUC: {auc:.4f} (target: >= 0.75)')\n",
    "print(f'Test Accuracy: {acc:.4f}')\n",
    "if auc >= 0.75:\n",
    "    print('✅ AUC-ROC LULUS NFR target (>= 0.75)')\n",
    "else:\n",
    "    print('❌ AUC-ROC belum mencapai target 0.75')\n",
    "\n",
    "bst.save_model('rejection_predictor.json')\n",
    "print('\\nModel saved to rejection_predictor.json')\n",
    "\n",
    "# Feature importance\n",
    "import matplotlib.pyplot as plt\n",
    "xgb.plot_importance(bst, max_num_features=15, title='Top 15 Rejection Risk Features')\n",
    "plt.tight_layout()\n",
    "plt.savefig('feature_importance.png', dpi=100)\n",
    "plt.show()\n"
  ]}
 ],
 "metadata": {
  "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open(r'c:\tradeflow-ai\tools\kaggle\nb5_xgboost.ipynb', 'w') as f:
    json.dump(nb5, f, indent=1)
print("nb5 written")
print("\\nAll notebooks regenerated successfully!")
